language: node_js
node_js:
  - "4.2"
install: true
services:
  - mongodb
notifications:
  recipients:
    - ezpaarse@couperin.org
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2644f77c080c05ce0ccf
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
