language: node_js
node_js:
  - "4.2"
install: true
services:
  - mongodb
notifications:
  recipients:
    - ezpaarse-team@googlegroups.com
    - dominique.lechaudel@gmail.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2644f77c080c05ce0ccf
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
  slack:
    secure: p/7J6LXqmmkQBaJ4q3KUibZgzKevo+ExTOiY+O4UQQa597dbK72gMWp+RKYVnfrhoMfTPD8oS8JG9nu74s6/mKHAtVc/g0qPH549tHpFC1DqD7G0TNUZxNV1tiWXkNbSPe59tkrn9R95azIA52cDXA1i9cguOYnCLysmEPUMQwU=
