language: node_js
node_js:
  - "4.2"
install: true
services:
  - mongodb
notifications:
  email:
    recipients:
      - ezpaarse-team@googlegroups.com
      - dominique.lechaudel@gmail.com
    on_success: change
    on_failure: always
  slack:
    secure: p/7J6LXqmmkQBaJ4q3KUibZgzKevo+ExTOiY+O4UQQa597dbK72gMWp+RKYVnfrhoMfTPD8oS8JG9nu74s6/mKHAtVc/g0qPH549tHpFC1DqD7G0TNUZxNV1tiWXkNbSPe59tkrn9R95azIA52cDXA1i9cguOYnCLysmEPUMQwU=
