site_name: ezPAARSE
repo_url: https://github.com/ezpaarse-project/ezpaarse
docs_dir: doc
theme: readthedocs

pages:
  - Introduction: index.md
  - Getting started:
    - Requirements:
      - Libraries: start/requirements.md
      - MongoDB: start/mongo.md
    - Installation: start/install.md
    - Startup: start/start.md
    - Set your log format: essential/formats.md
  - Essential things to know:
    - Glossary: essential/glossary.md
    - Knowledge bases: essential/knowledge-base.md
    - Job reports: essential/report.md
    - Typical EC attributes: essential/ec-attributes.md
  - Features:
    - Output fields: features/outputfields.md
    - Metadata enrichment: features/metadata-enrichment.md
    - Bot filtering: features/exclusions.md
    - COUNTER reports: features/counter.md
    - Alerts: features/alerts.md
    - Field splitter: features/userfields.md
    - Geolocation: features/geolocalisation.md
    - Double-click deduplication: features/doubleclick.md
    - EC qualification: features/qualification.md
  - Job parameters: configuration/parametres.md # to be replaced by features ?
  - Developer:
    - API:
      - Process: development/routes.md
      - Administration: development/admin.md
    - Makefile: development/makefile.md
    - Application core: development/core.md
    - Platforms: development/platforms.md
    - Middlewares: development/middlewares.md
    - Ecosystem: development/tools.md
    - Structure: development/tree.md
    - Website languages: development/multilinguisme.md
    - Changelog: development/changelog.md
